"""add_category_field_in_product_model

Revision ID: d34b82694cc1
Revises: fd46bdcc99d0
Create Date: 2026-09-23 07:04:43.343014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd34b82694cc1'
down_revision: Union[str, Sequence[str], None] = 'fd46bdcc99d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_inv_products', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_inv_products', 'category')
    # ### end Alembic commands ###
